spring:
  data:
    mongodb:
      username: miracle
      password: miracle
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
